### ISSUE TITLE
rusty_sr.exe cartoon_nn.png cartoon_nr.png  --custom anime.rsr   I use it like this???

### ISSUE THREAD

**Issue by c1a1o1** [millardjn/rusty_sr#4]
rusty_sr.exe cartoon_nn.png cartoon_nr.png  --custom anime.rsr   I use it like this???
Is it  some questions??

**Comment by millardjn** [comment]
Hi c1a1o1, 
The _nn images are nearest-neightbour upscaled images for display/comparison purposes, they wont upscale well because they have already been upscaled with pixelation included.

I've just uploaded the low resolution (_lr) images in /docs so you can reproduce the example images.
Try : `rusty_sr.exe --parameters anime cartoon_lr.png cartoon_nr.png`

Use `--custom __.rsr` only after you train a new neural network using the train subcommand.

**Comment by c1a1o1** [comment]
thanks very much,but  do you have  a email??  I  think your project is very great

**Comment by millardjn** [comment]
Yeah contact details are in the cargo.toml

**Comment by c1a1o1** [comment]
Thanks  very much
